# Generated by Django 5.0.1 on 2024-01-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='box',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
